/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      spacing: {
        pico: "6px",
        huge: "160px",
        micro: "12px",
        giant: "200px",
        atto: "2px",
        femto: "4px",
        xxxl: "120px",
        xl: "64px",
        nano: "8px",
        xxl: "80px",
        md: "48px",
        none: "0",
        sm: "40px",
        xxxs: "16px",
        xs: "32px",
        lg: "56px",
        xxs: "24px",
      },
      borderRadius: {
        none: "0",
        "extra-small": "2px",
        small: "4px",
        medium: "6px",
        large: "8px",
        "extra-large": "10px",
        pill: "500px",
        circular: "50%",
      },
      fontSize: {
        label: {
          medium: "16px",
          "extra-large": "20px",
          tiny: "10px",
          "extra-small": "12px",
          large: "18px",
          small: "14px",
        },
        paragraph: {
          tiny: "10px",
          small: "14px",
          medium: "16px",
          large: "18px",
          "extra-small": "12px",
        },
        heading: {
          1: "48px",
          2: "40px",
          3: "32px",
          4: "24px",
          5: "20px",
          6: "16px",
          "3-mobile": "26px",
          "2-mobile": "40px",
          "1-mobile": "48px",
          "6-mobile": "14px",
          "5-mobile": "18px",
          "4-mobile": "22px",
        },
      },
      colors: {
        mono: {
          white: "#ffffff",
          black: "#000000",
        },
        response: {
          success: "#36b37e",
          warning: "#ffab00",
          danger: "#ff5630",
        },
        neutrals: {
          "neutral-0": "#f9f9f9",
          "neutral-1": "#31131d",
          "neutral-2": "#3b2027",
          "neutral-3": "#493336",
          "neutral-4": "#564a4a",
          "neutral-5": "#666666",
          "neutral-6": "#a3a3a3",
          "neutral-7": "#d1d1d1",
          "neutral-8": "#efefef",
          "neutral-9": "#f7f7f7",
        },
        primary: {
          1: "#001b7c",
          2: "#002892",
          3: "#0039b7",
          4: "#014edc",
          5: "#0065ff",
          6: "#3e93fe",
          7: "#66aeff",
          8: "#99cdff",
          9: "#cce8fe",
          10: "#eaf9ff",
        },
        secondary: {
          1: "#050b25",
          2: "#09102c",
          3: "#0f1837",
          4: "#142141",
          5: "#1d2c4b",
          6: "#506793",
          7: "#809bca",
          8: "#b3caec",
          9: "#d8e5f6",
          10: "#f1f8fe",
        },
      },
    },
  },
  plugins: [],
};
